var quiz = {
  user: "Dave",
  questions: [
{
    text: "1 PROMAG TAB",
    responses: [
    { text: "A1", correct: true },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "2 DEGIROL",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4", correct: true },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "3 BECOM C ",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3", correct: true },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "4 INTUNAL TAB",
    responses: [
    { text: "A1" },
    { text: "A2", correct: true },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "5 MYCORAL CREAM",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5", correct: true },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "6 CDR 10S",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6", correct: true },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "7 ACTIFED SYR",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11", correct: true },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "8 DULCOLAX TAB",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9", correct: true },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "9 SUTRA KONDOM",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6", correct: true },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "10 STIMUNO SYR",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8", correct: true },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "11 FRESH CARE CITRUS",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9", correct: true },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "12 ONE MED TEST KEHAMILAN",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6", correct: true },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "13 SILADEX EXPECTORAN",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11", correct: true },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "14 SABUN ASEPSO",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12", correct: true },
    { text: "A13" }] },
{
    text: "15 NATURE E",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3", correct: true },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "16 TOLAK ANGIN CAIR",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4", correct: true },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "17 SALONPAS KOYO",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5", correct: true },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "18 THROMBOPOP GEL 20GR",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5", correct: true },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "19 PARACETAMOL TAB",
    responses: [
    { text: "A1" },
    { text: "A2", correct: true },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "20 VIOSTIN DS",
    responses: [
    { text: "A1" },
    { text: "A2", correct: true },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "21 COMBANTRIN",
    responses: [
    { text: "A1", correct: true },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "22 LELAP",
    responses: [
    { text: "A1", correct: true },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "23 FEMINAX TAB",
    responses: [
    { text: "A1", correct: true },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "24 CELANA SUNAT",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12", correct: true },
    { text: "A13" }] },
{
    text: "25 INSTO EYE DROP",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13", correct: true }] },
{
    text: "26 PEDITOX",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13", correct: true }] },
{
    text: "27 CETHAPIL GENTLE SKIN",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12", correct: true },
    { text: "A13" }] },
{
    text: "28 ANACETIN SYR",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10", correct: true },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "29 BLACKMORES PREGNANCY",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7", correct: true },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "30 MYLANTA SUSPENSI 50ML",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10", correct: true },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "31 LACOLDIN SYRUP",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A5" },
	{ text: "A6" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11", correct: true },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "32 HANSAPLAS JUMBO KAIN ELASTIS ",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A14" },
	{ text: "A15" },
	{ text: "A6", correct: true },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "33 SARI KURMA SAHARA",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A14" },
	{ text: "A15", correct: true },
	{ text: "A16" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "34 MINOSEP GARGLE",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A14", correct: true },
	{ text: "A15" },
	{ text: "A16" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "35 MINYAK KAPAK",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A14" },
	{ text: "A15", correct: true },
	{ text: "A16" },
	{ text: "A17" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "36 BEDAK HEROCIN",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A15", correct: true },
	{ text: "A16" },
	{ text: "A17" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "37 HAU FUNG SAN",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A14" },
	{ text: "A15", correct: true },
	{ text: "A16" },
	{ text: "A7" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },

{
    text: "38 BEDAK MBK",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A4" },
	{ text: "A15", correct: true },
	{ text: "A61" },
	{ text: "A17" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "39 PURE BABY DECONGESTAN",
    responses: [
    { text: "A1" },
    { text: "A2" },
	{ text: "A3" },
	{ text: "A14", correct: true },
	{ text: "A15" },
	{ text: "A16" },
	{ text: "A17" },
	{ text: "A8" },
    { text: "A9" },
	{ text: "A10" },
	{ text: "A11" },
	{ text: "A12" },
    { text: "A13" }] },
{
    text: "40 NEPHROLIT CAP",
    responses: [
    { text: "A1", correct: true },
    { text: "A10" },
    { text: "A9" },
    { text: "A7" }] }] },




userResponseSkelaton = Array(quiz.questions.length).fill(null);

var app = new Vue({
  el: "#app",
  data: {
    quiz: quiz,
    questionIndex: 0,
    userResponses: userResponseSkelaton,
    isActive: false },

  filters: {
    charIndex: function (i) {
      return String.fromCharCode(97 + i);
    } },

  methods: {
    restart: function () {
      this.questionIndex = 0;
      this.userResponses = Array(this.quiz.questions.length).fill(null);
    },
    selectOption: function (index) {
      Vue.set(this.userResponses, this.questionIndex, index);
      //console.log(this.userResponses);
    },
    next: function () {
      if (this.questionIndex < this.quiz.questions.length)
      this.questionIndex++;
    },

    prev: function () {
      if (this.quiz.questions.length > 0) this.questionIndex--;
    },
    // Return "true" count in userResponses
    score: function () {
      var score = 0;
      for (let i = 0; i < this.userResponses.length; i++) {
        if (
        typeof this.quiz.questions[i].responses[
        this.userResponses[i]] !==
        "undefined" &&
        this.quiz.questions[i].responses[this.userResponses[i]].correct)
        {
          score = score + 1;
        }
      }
      return score;

      //return this.userResponses.filter(function(val) { return val }).length;
    } } });